server:
host: 0.0.0.0
port: 8443
tls:
cert_file: config/certs/dev-cert.pem
key_file: config/certs/dev-key.pem
client_mtla: false


routing:
- match: "^/v1/auth/.*"
target: auth
- match: "^/v1/rt/connect$"
target: messaging
upgrade: websocket
- match: ".*"
target: files


upstreams:
auth:
kind: http
transport: uds
socket: "/run/securecloud/auth.sock"
messaging:
kind: ws
transport: tcp
address: "messaging:8081"
files:
kind: http
transport: uds
socket: "/run/securecloud/files.sock"


security:
jwks:
cache_ttl_s: 300
providers: [] # pour le kit: non utilisé


observability:
prometheus:
bind: "0.0.0.0:9090"
logs:
level: info